name: Deploy app to heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
          heroku_email: "abayomexy@gmail.com"
        env:
          HD_NODE_ENV: ${{secrets.NODE_ENV}}
          HD_JWT_SECRET: ${{secrets.JWT_SECRET}}
          HD_JWT_EXPIRY: ${{secrets.JWT_EXPIRY}}
          HD_ORIGIN: ${{secrets.ORIGIN}}
          HD_API_KEY: ${{secrets.API_KEY}}
          HD_API_SECRET: ${{secrets.API_SECRET}}
          HD_DATABASE_URL: ${{secrets.DATABASE_URL}}
          HD_PAYPAL_ClientId: ${{secrets.PAYPAL_ClientId}}
          HD_PAYPAL_Secret: ${{secrets.PAYPAL_Secret}}
